import { Sessao } from "./tiposSessoes";

export const SESSOES_INICIAIS: Sessao[] = [
  {
    id: "s1",
    criancaId: "1",
    criancaNome: "Lucas Andrade",
    profissionalId: "p1",
    profissionalNome: "Dra. Ana Souza",
    data: new Date().toISOString().split("T")[0],
    horaInicio: "09:00",
    horaFim: "09:50",
    duracaoMin: 50,
    tipo: "ABA",
    local: "clinica",
    sala: "Sala 2",
    status: "concluida",
    humor: "bom",
    notaGeral:
      "Lucas chegou bem disposto. Boa adesão às atividades de pareamento. Manteve atenção sustentada por 12 minutos.",
    evolucaoDiaria:
      "Demonstrou progresso na transição entre atividades sem necessidade de suporte gestual. PECS nível 3 estável.",
    registros: [
      {
        programaId: "pg1",
        programaNome: "Comunicação Funcional - PECS",
        objetivo: "Solicitar item preferido com 3 figuras",
        tentativas: 10,
        acertos: 8,
        nivel: "IND",
        observacao: "Excelente generalização entre estímulos.",
      },
      {
        programaId: "pg2",
        programaNome: "Habilidades Sociais",
        objetivo: "Manter contato visual por 5s",
        tentativas: 8,
        acertos: 5,
        nivel: "AG",
      },
    ],
    narrativaAbc: [
      {
        id: "abc1",
        horario: "09:22",
        antecedente: "Solicitada troca de atividade (encerrar tablet).",
        comportamento: "Choro breve e empurrou o material.",
        consequencia: "Aplicado suporte visual com timer e oferecido reforçador secundário.",
        intensidade: "leve",
      },
    ],
    reforcadores: [
      { nome: "Elogio entusiasmado", tipo: "social", efetividade: 5 },
      { nome: "Massinha de modelar", tipo: "tangivel", efetividade: 4 },
      { nome: "Bolacha recheada", tipo: "comestivel", efetividade: 3 },
    ],
    anexos: [{ nome: "registro_pecs.jpg", tipo: "imagem" }],
  },
  {
    id: "s2",
    criancaId: "2",
    criancaNome: "Sofia Martins",
    profissionalId: "p2",
    profissionalNome: "Dr. Carlos Lima",
    data: new Date().toISOString().split("T")[0],
    horaInicio: "10:00",
    horaFim: "10:40",
    duracaoMin: 40,
    tipo: "Fono",
    local: "clinica",
    sala: "Sala 1",
    status: "em_andamento",
    humor: "otimo",
    notaGeral: "Sessão focada em fonemas bilabiais. Sofia bastante engajada.",
    registros: [
      {
        programaId: "pg3",
        programaNome: "Articulação - Fonemas",
        objetivo: "Produzir /p/ em sílabas iniciais",
        tentativas: 12,
        acertos: 10,
        nivel: "IND",
      },
    ],
    narrativaAbc: [],
    reforcadores: [{ nome: "Adesivos", tipo: "tangivel", efetividade: 5 }],
    anexos: [],
  },
  {
    id: "s3",
    criancaId: "3",
    criancaNome: "Pedro Henrique",
    profissionalId: "p1",
    profissionalNome: "Dra. Ana Souza",
    data: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    horaInicio: "14:00",
    horaFim: "14:50",
    duracaoMin: 50,
    tipo: "ABA",
    local: "clinica",
    sala: "Sala 3",
    status: "concluida",
    humor: "ansioso",
    notaGeral: "Pedro chegou agitado após mudança na rotina escolar.",
    notaIncidente: "Episódio de auto-agressão (tapa na cabeça) ao recusar atividade. Resolvido com técnica de redirecionamento.",
    evolucaoDiaria: "Necessária reavaliação dos critérios de demanda. Considerar dessensibilização gradual.",
    registros: [
      {
        programaId: "pg4",
        programaNome: "Tolerância à Frustração",
        objetivo: "Aceitar 'não' sem comportamento disruptivo",
        tentativas: 6,
        acertos: 2,
        nivel: "AFL",
        observacao: "Regressão em relação à última sessão.",
      },
    ],
    narrativaAbc: [
      {
        id: "abc2",
        horario: "14:18",
        antecedente: "Negada solicitação de sair da sala.",
        comportamento: "Auto-agressão (3 tapas na cabeça) e gritos.",
        consequencia: "Bloqueio físico seguro, ambiente neutralizado, reforço diferencial após 30s de calma.",
        intensidade: "moderada",
      },
    ],
    reforcadores: [{ nome: "Pausa sensorial", tipo: "atividade", efetividade: 4 }],
    anexos: [],
  },
  {
    id: "s4",
    criancaId: "1",
    criancaNome: "Lucas Andrade",
    profissionalId: "p3",
    profissionalNome: "TO Mariana Reis",
    data: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    horaInicio: "15:00",
    horaFim: "15:50",
    duracaoMin: 50,
    tipo: "TO",
    local: "clinica",
    sala: "Sala Sensorial",
    status: "agendada",
    registros: [],
    narrativaAbc: [],
    reforcadores: [],
    anexos: [],
  },
];

export const PROFISSIONAIS_DISPONIVEIS = [
  { id: "p1", nome: "Dra. Ana Souza" },
  { id: "p2", nome: "Dr. Carlos Lima" },
  { id: "p3", nome: "TO Mariana Reis" },
  { id: "p4", nome: "Psic. João Pereira" },
];

export const CRIANCAS_DISPONIVEIS = [
  { id: "1", nome: "Lucas Andrade" },
  { id: "2", nome: "Sofia Martins" },
  { id: "3", nome: "Pedro Henrique" },
];
