import { ComunicacaoFamilia, MembroFamilia } from "./tiposFamilia";

export const familiasMock: MembroFamilia[] = [
  {
    id: "fa1",
    nome: "Patrícia Mendes",
    parentesco: "Mãe",
    email: "patricia.mendes@email.com",
    telefone: "(11) 98888-1111",
    cpf: "123.456.789-00",
    profissao: "Pedagoga",
    recebeRelatorios: true,
    participaOrientacoes: true,
    statusAcessoApp: "ativo",
    ultimoAcesso: "2026-04-21",
    criancas: [{ criancaId: "1", nome: "Lucas Mendes", principal: true }],
    iniciais: "PM",
    observacoes: "Prefere contato por WhatsApp no período da tarde.",
  },
  {
    id: "fa2",
    nome: "Roberto Mendes",
    parentesco: "Pai",
    email: "roberto.mendes@email.com",
    telefone: "(11) 97777-2222",
    profissao: "Engenheiro",
    recebeRelatorios: true,
    participaOrientacoes: false,
    statusAcessoApp: "convite_enviado",
    criancas: [{ criancaId: "1", nome: "Lucas Mendes", principal: false }],
    iniciais: "RM",
  },
  {
    id: "fa3",
    nome: "Carolina Silva",
    parentesco: "Mãe",
    email: "carolina.silva@email.com",
    telefone: "(11) 96666-3333",
    cpf: "987.654.321-00",
    profissao: "Médica",
    recebeRelatorios: true,
    participaOrientacoes: true,
    statusAcessoApp: "ativo",
    ultimoAcesso: "2026-04-22",
    criancas: [{ criancaId: "2", nome: "Maria Silva", principal: true }],
    iniciais: "CS",
  },
  {
    id: "fa4",
    nome: "Débora Rocha",
    parentesco: "Mãe",
    email: "debora.rocha@email.com",
    telefone: "(11) 95555-4444",
    profissao: "Designer",
    recebeRelatorios: true,
    participaOrientacoes: true,
    statusAcessoApp: "ativo",
    ultimoAcesso: "2026-04-20",
    criancas: [{ criancaId: "3", nome: "Pedro Rocha", principal: true }],
    iniciais: "DR",
  },
  {
    id: "fa5",
    nome: "Marcelo Santos",
    parentesco: "Pai",
    email: "marcelo.santos@email.com",
    telefone: "(11) 94444-5555",
    profissao: "Advogado",
    recebeRelatorios: false,
    participaOrientacoes: true,
    statusAcessoApp: "sem_acesso",
    criancas: [{ criancaId: "4", nome: "Julia Santos", principal: true }],
    iniciais: "MS",
    observacoes: "Pais separados — comunicação direta com o pai.",
  },
  {
    id: "fa6",
    nome: "Helena Almeida",
    parentesco: "Avó",
    email: "helena.almeida@email.com",
    telefone: "(11) 93333-6666",
    recebeRelatorios: false,
    participaOrientacoes: false,
    statusAcessoApp: "sem_acesso",
    criancas: [{ criancaId: "6", nome: "Sofia Almeida", principal: true }],
    iniciais: "HA",
    observacoes: "Responsável legal da Sofia.",
  },
  {
    id: "fa7",
    nome: "Renata Oliveira",
    parentesco: "Mãe",
    email: "renata.oliveira@email.com",
    telefone: "(11) 92222-7777",
    profissao: "Professora",
    recebeRelatorios: true,
    participaOrientacoes: true,
    statusAcessoApp: "bloqueado",
    criancas: [{ criancaId: "5", nome: "Gabriel Oliveira", principal: true }],
    iniciais: "RO",
  },
];

export const comunicacoesMock: ComunicacaoFamilia[] = [
  {
    id: "c1",
    membroId: "fa1",
    data: "2026-04-22",
    tipo: "reuniao",
    assunto: "Devolutiva mensal de evolução",
    resumo:
      "Apresentado avanço de mando funcional e novas metas para o próximo mês.",
    responsavelClinica: "Dra. Ana Souza",
  },
  {
    id: "c2",
    membroId: "fa3",
    data: "2026-04-20",
    tipo: "mensagem",
    assunto: "Orientação sobre rotina em casa",
    resumo:
      "Enviado material com sugestões de generalização das habilidades trabalhadas.",
    responsavelClinica: "Dr. Carlos Lima",
  },
  {
    id: "c3",
    membroId: "fa4",
    data: "2026-04-18",
    tipo: "ligacao",
    assunto: "Confirmação de horário",
    resumo: "Reagendamento da sessão de quinta para sexta às 15h.",
    responsavelClinica: "Mariana Alves",
  },
  {
    id: "c4",
    membroId: "fa5",
    data: "2026-04-15",
    tipo: "email",
    assunto: "Relatório trimestral disponível",
    resumo:
      "Enviado relatório consolidado do trimestre com gráficos de desempenho.",
    responsavelClinica: "Dra. Fernanda Costa",
  },
];

export const parentescosDisponiveis: MembroFamilia["parentesco"][] = [
  "Mãe",
  "Pai",
  "Avó",
  "Avô",
  "Tio(a)",
  "Responsável legal",
  "Outro",
];
