import { Agendamento, coresTipoSessao } from "./tiposAgenda";
import {
  addDays,
  startOfWeek,
  setHours,
  setMinutes,
} from "date-fns";

const base = startOfWeek(new Date(), { weekStartsOn: 1 });

function criarData(diaSemana: number, hora: number, minuto: number = 0): Date {
  return setMinutes(setHours(addDays(base, diaSemana), hora), minuto);
}

export const agendamentosSemente: Agendamento[] = [
  {
    id: "ag1",
    criancaId: "1",
    criancaNome: "Lucas Mendes",
    profissionalId: "p1",
    profissionalNome: "Dra. Ana Souza",
    tipo: "ABA Individual",
    sala: "Sala 1 — ABA",
    dataInicio: criarData(0, 8, 0),
    dataFim: criarData(0, 9, 0),
    status: "confirmado",
    cor: coresTipoSessao["ABA Individual"],
    recorrencia: { tipo: "semanal", diasSemana: [1, 3, 5] },
  },
  {
    id: "ag2",
    criancaId: "2",
    criancaNome: "Maria Silva",
    profissionalId: "p2",
    profissionalNome: "Dr. Carlos Lima",
    tipo: "Fonoaudiologia",
    sala: "Sala 3 — Fono",
    dataInicio: criarData(0, 9, 0),
    dataFim: criarData(0, 10, 0),
    status: "confirmado",
    cor: coresTipoSessao["Fonoaudiologia"],
  },
  {
    id: "ag3",
    criancaId: "3",
    criancaNome: "Pedro Rocha",
    profissionalId: "p3",
    profissionalNome: "Dra. Fernanda Costa",
    tipo: "Terapia Ocupacional",
    sala: "Sala 4 — TO",
    dataInicio: criarData(1, 10, 0),
    dataFim: criarData(1, 11, 0),
    status: "pendente",
    cor: coresTipoSessao["Terapia Ocupacional"],
  },
  {
    id: "ag4",
    criancaId: "1",
    criancaNome: "Lucas Mendes",
    profissionalId: "p1",
    profissionalNome: "Dra. Ana Souza",
    tipo: "ABA Individual",
    sala: "Sala 1 — ABA",
    dataInicio: criarData(2, 8, 0),
    dataFim: criarData(2, 9, 0),
    status: "confirmado",
    cor: coresTipoSessao["ABA Individual"],
  },
  {
    id: "ag5",
    criancaId: "4",
    criancaNome: "Julia Santos",
    profissionalId: "p4",
    profissionalNome: "Dr. Paulo Dias",
    tipo: "Psicologia",
    sala: "Sala 5 — Psicologia",
    dataInicio: criarData(1, 14, 0),
    dataFim: criarData(1, 15, 0),
    status: "confirmado",
    cor: coresTipoSessao["Psicologia"],
  },
  {
    id: "ag6",
    criancaId: "5",
    criancaNome: "Gabriel Oliveira",
    profissionalId: "p5",
    profissionalNome: "Dra. Mariana Alves",
    tipo: "ABA Individual",
    sala: "Sala 2 — ABA",
    dataInicio: criarData(3, 8, 0),
    dataFim: criarData(3, 9, 30),
    status: "confirmado",
    cor: coresTipoSessao["ABA Individual"],
  },
  {
    id: "ag7",
    criancaId: "2",
    criancaNome: "Maria Silva",
    profissionalId: "p1",
    profissionalNome: "Dra. Ana Souza",
    tipo: "Supervisão",
    sala: "Sala Grupo",
    dataInicio: criarData(4, 13, 0),
    dataFim: criarData(4, 14, 30),
    status: "pendente",
    cor: coresTipoSessao["Supervisão"],
  },
  {
    id: "ag8",
    criancaId: "6",
    criancaNome: "Sofia Almeida",
    profissionalId: "p3",
    profissionalNome: "Dra. Fernanda Costa",
    tipo: "Avaliação",
    sala: "Sala 4 — TO",
    dataInicio: criarData(4, 9, 0),
    dataFim: criarData(4, 10, 30),
    status: "confirmado",
    cor: coresTipoSessao["Avaliação"],
  },
  {
    id: "ag9",
    criancaId: "3",
    criancaNome: "Pedro Rocha",
    profissionalId: "p5",
    profissionalNome: "Dra. Mariana Alves",
    tipo: "ABA Grupo",
    sala: "Sala Grupo",
    dataInicio: criarData(2, 15, 0),
    dataFim: criarData(2, 16, 30),
    status: "confirmado",
    cor: coresTipoSessao["ABA Grupo"],
  },
];
