import { Funcionario } from "./tiposFuncionarios";

export const funcionariosMock: Funcionario[] = [
  {
    id: "f1",
    nome: "Dra. Ana Souza",
    email: "ana.souza@trackaba.com",
    telefone: "(11) 98765-4321",
    cargo: "Analista de Comportamento",
    registroProfissional: "BCBA 1-23-45678",
    especialidades: ["TEA", "Manejo de comportamentos", "PECS"],
    status: "ativo",
    nivelAcesso: "clinico",
    dataAdmissao: "2023-02-15",
    cargaHorariaSemanal: 40,
    criancasAtendidas: 8,
    sessoesNoMes: 64,
    iniciais: "AS",
  },
  {
    id: "f2",
    nome: "Dr. Carlos Lima",
    email: "carlos.lima@trackaba.com",
    telefone: "(11) 99876-1234",
    cargo: "Psicólogo(a)",
    registroProfissional: "CRP 06/123456",
    especialidades: ["Avaliação cognitiva", "TEA", "TDAH"],
    status: "ativo",
    nivelAcesso: "clinico",
    dataAdmissao: "2022-08-01",
    cargaHorariaSemanal: 36,
    criancasAtendidas: 6,
    sessoesNoMes: 48,
    iniciais: "CL",
  },
  {
    id: "f3",
    nome: "Dra. Fernanda Costa",
    email: "fernanda.costa@trackaba.com",
    telefone: "(11) 97654-9876",
    cargo: "Coordenador(a) Clínico(a)",
    registroProfissional: "BCBA 1-22-11122",
    especialidades: ["Supervisão", "VB-MAPP", "ABLLS-R"],
    status: "ativo",
    nivelAcesso: "admin",
    dataAdmissao: "2021-03-10",
    cargaHorariaSemanal: 44,
    criancasAtendidas: 4,
    sessoesNoMes: 28,
    iniciais: "FC",
  },
  {
    id: "f4",
    nome: "Dr. Paulo Dias",
    email: "paulo.dias@trackaba.com",
    telefone: "(11) 98123-4567",
    cargo: "Terapeuta ABA",
    especialidades: ["DTT", "NET", "Treino de pais"],
    status: "ativo",
    nivelAcesso: "operacional",
    dataAdmissao: "2024-01-22",
    cargaHorariaSemanal: 30,
    criancasAtendidas: 5,
    sessoesNoMes: 40,
    iniciais: "PD",
  },
  {
    id: "f5",
    nome: "Juliana Martins",
    email: "juliana.martins@trackaba.com",
    telefone: "(11) 99988-7766",
    cargo: "Fonoaudiólogo(a)",
    registroProfissional: "CRFa 2-12345",
    especialidades: ["Comunicação alternativa", "PECS", "Linguagem"],
    status: "ferias",
    nivelAcesso: "clinico",
    dataAdmissao: "2023-06-05",
    cargaHorariaSemanal: 30,
    criancasAtendidas: 7,
    sessoesNoMes: 0,
    iniciais: "JM",
  },
  {
    id: "f6",
    nome: "Roberto Ferreira",
    email: "roberto.ferreira@trackaba.com",
    telefone: "(11) 97777-3333",
    cargo: "Terapeuta Ocupacional",
    registroProfissional: "CREFITO 3/12345-TO",
    especialidades: ["Integração sensorial", "AVD"],
    status: "ativo",
    nivelAcesso: "operacional",
    dataAdmissao: "2024-09-01",
    cargaHorariaSemanal: 25,
    criancasAtendidas: 4,
    sessoesNoMes: 32,
    iniciais: "RF",
  },
  {
    id: "f7",
    nome: "Mariana Alves",
    email: "mariana.alves@trackaba.com",
    telefone: "(11) 98444-5555",
    cargo: "Recepção",
    especialidades: ["Atendimento", "Agendamento"],
    status: "ativo",
    nivelAcesso: "operacional",
    dataAdmissao: "2024-04-12",
    cargaHorariaSemanal: 40,
    criancasAtendidas: 0,
    sessoesNoMes: 0,
    iniciais: "MA",
  },
  {
    id: "f8",
    nome: "Tiago Nunes",
    email: "tiago.nunes@trackaba.com",
    telefone: "(11) 96666-2222",
    cargo: "Terapeuta ABA",
    especialidades: ["DTT", "Reforço diferencial"],
    status: "afastado",
    nivelAcesso: "operacional",
    dataAdmissao: "2023-11-20",
    cargaHorariaSemanal: 30,
    criancasAtendidas: 0,
    sessoesNoMes: 0,
    iniciais: "TN",
  },
];

export const cargosDisponiveis: Funcionario["cargo"][] = [
  "Analista de Comportamento",
  "Terapeuta ABA",
  "Psicólogo(a)",
  "Fonoaudiólogo(a)",
  "Terapeuta Ocupacional",
  "Coordenador(a) Clínico(a)",
  "Supervisor(a)",
  "Recepção",
  "Administrativo",
];

export const niveisAcessoDisponiveis: Funcionario["nivelAcesso"][] = [
  "admin",
  "clinico",
  "operacional",
  "visualizador",
];
