import { Programa } from "./tiposProgramas";

// Biblioteca padrão de programas reutilizáveis na clínica
export const BIBLIOTECA_PROGRAMAS: Programa[] = [
  {
    id: "bib-1",
    nome: "Contato Visual",
    disciplina: "ABA",
    tipo: "Aquisição",
    status: "ativo",
    objetivoGeral: "Manter contato visual por 5 segundos quando chamado pelo nome",
    descricao:
      "Programa para desenvolver e manter contato visual funcional como pré-requisito para aprendizagem.",
    objetivos: [
      { id: "o1", descricao: "Olhar para o terapeuta por 1 segundo", criterio: "8/10 tentativas", concluido: false },
      { id: "o2", descricao: "Manter contato por 3 segundos", criterio: "8/10 tentativas", concluido: false },
      { id: "o3", descricao: "Manter contato por 5 segundos", criterio: "9/10 em 3 sessões", concluido: false },
    ],
    tentativasPorSessao: 10,
    criterioMaestria: "90% de acerto em 3 sessões consecutivas",
    criadoEm: "2024-08-01",
    criadoPor: "Biblioteca",
    ordem: 0,
  },
  {
    id: "bib-2",
    nome: "Imitação Motora Grossa",
    disciplina: "ABA",
    tipo: "Aquisição",
    status: "ativo",
    objetivoGeral: "Imitar 10 movimentos motores grossos sob comando",
    descricao: "Desenvolvimento da imitação como habilidade pivot para aquisições futuras.",
    objetivos: [
      { id: "o1", descricao: "Imitar bater palmas", criterio: "9/10 tentativas", concluido: false },
      { id: "o2", descricao: "Imitar levantar os braços", criterio: "9/10 tentativas", concluido: false },
    ],
    tentativasPorSessao: 10,
    criterioMaestria: "90% em 3 sessões",
    criadoEm: "2024-08-01",
    criadoPor: "Biblioteca",
    ordem: 1,
  },
  {
    id: "bib-3",
    nome: "Pedido com PECS - Fase I",
    disciplina: "Fonoaudiologia",
    tipo: "Aquisição",
    status: "ativo",
    objetivoGeral: "Realizar pedidos espontâneos utilizando cartões PECS",
    descricao: "Sistema de comunicação por troca de figuras para iniciantes em comunicação aumentativa.",
    objetivos: [
      { id: "o1", descricao: "Entregar cartão na mão do parceiro", criterio: "10/10 com 1 ajudante", concluido: false },
    ],
    tentativasPorSessao: 8,
    criterioMaestria: "100% sem ajuda em 3 sessões",
    criadoEm: "2024-08-05",
    criadoPor: "Biblioteca",
    ordem: 2,
  },
  {
    id: "bib-4",
    nome: "Coordenação Motora Fina - Pinça",
    disciplina: "Terapia Ocupacional",
    tipo: "Aquisição",
    status: "ativo",
    objetivoGeral: "Realizar movimento de pinça com precisão para manipular objetos pequenos",
    descricao: "Desenvolvimento da preensão tipo pinça para atividades de vida diária e escrita.",
    objetivos: [
      { id: "o1", descricao: "Pegar contas grandes", criterio: "8/10", concluido: false },
      { id: "o2", descricao: "Pegar grãos pequenos", criterio: "8/10", concluido: false },
    ],
    tentativasPorSessao: 10,
    criterioMaestria: "80% em 3 sessões",
    criadoEm: "2024-08-10",
    criadoPor: "Biblioteca",
    ordem: 3,
  },
  {
    id: "bib-5",
    nome: "Tolerância à Espera",
    disciplina: "Psicologia",
    tipo: "Aquisição",
    status: "ativo",
    objetivoGeral: "Esperar por reforço por até 2 minutos sem comportamento interferente",
    descricao: "Desenvolvimento de autorregulação e tolerância à frustração.",
    objetivos: [
      { id: "o1", descricao: "Esperar 30 segundos", criterio: "8/10", concluido: false },
      { id: "o2", descricao: "Esperar 1 minuto", criterio: "8/10", concluido: false },
      { id: "o3", descricao: "Esperar 2 minutos", criterio: "8/10", concluido: false },
    ],
    tentativasPorSessao: 5,
    criterioMaestria: "80% em 3 sessões consecutivas",
    criadoEm: "2024-08-12",
    criadoPor: "Biblioteca",
    ordem: 4,
  },
  {
    id: "bib-6",
    nome: "Leitura Funcional",
    disciplina: "Psicopedagogia",
    tipo: "Aquisição",
    status: "ativo",
    objetivoGeral: "Reconhecer e ler 30 palavras funcionais do cotidiano",
    descricao: "Aquisição de leitura global de palavras funcionais relevantes para autonomia.",
    objetivos: [
      { id: "o1", descricao: "Ler 10 palavras de comida", criterio: "9/10", concluido: false },
      { id: "o2", descricao: "Ler 10 palavras de locais", criterio: "9/10", concluido: false },
    ],
    tentativasPorSessao: 10,
    criterioMaestria: "90% em 2 sessões",
    criadoEm: "2024-08-15",
    criadoPor: "Biblioteca",
    ordem: 5,
  },
];

// Programas atribuídos a uma criança (exemplo: Lucas Andrade id=1)
export const PROGRAMAS_CRIANCA_INICIAIS: Programa[] = [
  {
    ...BIBLIOTECA_PROGRAMAS[0],
    id: "pc-1",
    criancaId: "1",
    baseadoEm: "bib-1",
    criadoPor: "Dra. Marina",
    criadoEm: "2024-09-01",
    ordem: 0,
  },
  {
    ...BIBLIOTECA_PROGRAMAS[1],
    id: "pc-2",
    criancaId: "1",
    baseadoEm: "bib-2",
    criadoPor: "Dra. Marina",
    criadoEm: "2024-09-10",
    ordem: 1,
  },
];

export const CORES_DISCIPLINA: Record<string, string> = {
  ABA: "bg-primary/10 text-primary border-primary/20",
  Fonoaudiologia: "bg-secondary/10 text-secondary border-secondary/20",
  "Terapia Ocupacional": "bg-accent/20 text-accent-foreground border-accent/30",
  Psicologia: "bg-status-info/10 text-status-info border-status-info/20",
  Psicopedagogia: "bg-status-warning/10 text-status-warning border-status-warning/20",
};
